apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-event-portal.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  MONGO_URI: {{ .Values.config.mongoUri | quote }}
  VITE_API_URL: "/api"
